/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotRouteImport } from './routes/_auth/forgot'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as ApppagesDashboardsSalesIndexRouteImport } from './routes/_app/(pages)/dashboards/sales/index'
import { Route as ApppagesDashboardsOrdersIndexRouteImport } from './routes/_app/(pages)/dashboards/orders/index'
import { Route as ApppagesDashboardsCrmAnalyticsIndexRouteImport } from './routes/_app/(pages)/dashboards/crm-analytics/index'
import { Route as ApppagesDashboardsCmsAnalyticsIndexRouteImport } from './routes/_app/(pages)/dashboards/cms-analytics/index'
import { Route as ApppagesSettingsSectionsAppearanceRouteImport } from './routes/_app/(pages)/settings/_sections/Appearance'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApppagesDashboardsSalesIndexRoute =
  ApppagesDashboardsSalesIndexRouteImport.update({
    id: '/(pages)/dashboards/sales/',
    path: '/dashboards/sales/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApppagesDashboardsOrdersIndexRoute =
  ApppagesDashboardsOrdersIndexRouteImport.update({
    id: '/(pages)/dashboards/orders/',
    path: '/dashboards/orders/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApppagesDashboardsCrmAnalyticsIndexRoute =
  ApppagesDashboardsCrmAnalyticsIndexRouteImport.update({
    id: '/(pages)/dashboards/crm-analytics/',
    path: '/dashboards/crm-analytics/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApppagesDashboardsCmsAnalyticsIndexRoute =
  ApppagesDashboardsCmsAnalyticsIndexRouteImport.update({
    id: '/(pages)/dashboards/cms-analytics/',
    path: '/dashboards/cms-analytics/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApppagesSettingsSectionsAppearanceRoute =
  ApppagesSettingsSectionsAppearanceRouteImport.update({
    id: '/(pages)/settings/_sections/Appearance',
    path: '/settings/Appearance',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/profile': typeof AppProfileRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/settings/Appearance': typeof ApppagesSettingsSectionsAppearanceRoute
  '/dashboards/cms-analytics': typeof ApppagesDashboardsCmsAnalyticsIndexRoute
  '/dashboards/crm-analytics': typeof ApppagesDashboardsCrmAnalyticsIndexRoute
  '/dashboards/orders': typeof ApppagesDashboardsOrdersIndexRoute
  '/dashboards/sales': typeof ApppagesDashboardsSalesIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof AppProfileRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/settings/Appearance': typeof ApppagesSettingsSectionsAppearanceRoute
  '/dashboards/cms-analytics': typeof ApppagesDashboardsCmsAnalyticsIndexRoute
  '/dashboards/crm-analytics': typeof ApppagesDashboardsCrmAnalyticsIndexRoute
  '/dashboards/orders': typeof ApppagesDashboardsOrdersIndexRoute
  '/dashboards/sales': typeof ApppagesDashboardsSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_auth/forgot': typeof AuthForgotRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/(pages)/settings/_sections/Appearance': typeof ApppagesSettingsSectionsAppearanceRoute
  '/_app/(pages)/dashboards/cms-analytics/': typeof ApppagesDashboardsCmsAnalyticsIndexRoute
  '/_app/(pages)/dashboards/crm-analytics/': typeof ApppagesDashboardsCrmAnalyticsIndexRoute
  '/_app/(pages)/dashboards/orders/': typeof ApppagesDashboardsOrdersIndexRoute
  '/_app/(pages)/dashboards/sales/': typeof ApppagesDashboardsSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/forgot'
    | '/login'
    | '/otp'
    | '/register'
    | '/settings/Appearance'
    | '/dashboards/cms-analytics'
    | '/dashboards/crm-analytics'
    | '/dashboards/orders'
    | '/dashboards/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/forgot'
    | '/login'
    | '/otp'
    | '/register'
    | '/settings/Appearance'
    | '/dashboards/cms-analytics'
    | '/dashboards/crm-analytics'
    | '/dashboards/orders'
    | '/dashboards/sales'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/profile'
    | '/_auth/forgot'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_auth/register'
    | '/_app/(pages)/settings/_sections/Appearance'
    | '/_app/(pages)/dashboards/cms-analytics/'
    | '/_app/(pages)/dashboards/crm-analytics/'
    | '/_app/(pages)/dashboards/orders/'
    | '/_app/(pages)/dashboards/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot': {
      id: '/_auth/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(pages)/dashboards/sales/': {
      id: '/_app/(pages)/dashboards/sales/'
      path: '/dashboards/sales'
      fullPath: '/dashboards/sales'
      preLoaderRoute: typeof ApppagesDashboardsSalesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(pages)/dashboards/orders/': {
      id: '/_app/(pages)/dashboards/orders/'
      path: '/dashboards/orders'
      fullPath: '/dashboards/orders'
      preLoaderRoute: typeof ApppagesDashboardsOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(pages)/dashboards/crm-analytics/': {
      id: '/_app/(pages)/dashboards/crm-analytics/'
      path: '/dashboards/crm-analytics'
      fullPath: '/dashboards/crm-analytics'
      preLoaderRoute: typeof ApppagesDashboardsCrmAnalyticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(pages)/dashboards/cms-analytics/': {
      id: '/_app/(pages)/dashboards/cms-analytics/'
      path: '/dashboards/cms-analytics'
      fullPath: '/dashboards/cms-analytics'
      preLoaderRoute: typeof ApppagesDashboardsCmsAnalyticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(pages)/settings/_sections/Appearance': {
      id: '/_app/(pages)/settings/_sections/Appearance'
      path: '/settings/Appearance'
      fullPath: '/settings/Appearance'
      preLoaderRoute: typeof ApppagesSettingsSectionsAppearanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  ApppagesSettingsSectionsAppearanceRoute: typeof ApppagesSettingsSectionsAppearanceRoute
  ApppagesDashboardsCmsAnalyticsIndexRoute: typeof ApppagesDashboardsCmsAnalyticsIndexRoute
  ApppagesDashboardsCrmAnalyticsIndexRoute: typeof ApppagesDashboardsCrmAnalyticsIndexRoute
  ApppagesDashboardsOrdersIndexRoute: typeof ApppagesDashboardsOrdersIndexRoute
  ApppagesDashboardsSalesIndexRoute: typeof ApppagesDashboardsSalesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  ApppagesSettingsSectionsAppearanceRoute:
    ApppagesSettingsSectionsAppearanceRoute,
  ApppagesDashboardsCmsAnalyticsIndexRoute:
    ApppagesDashboardsCmsAnalyticsIndexRoute,
  ApppagesDashboardsCrmAnalyticsIndexRoute:
    ApppagesDashboardsCrmAnalyticsIndexRoute,
  ApppagesDashboardsOrdersIndexRoute: ApppagesDashboardsOrdersIndexRoute,
  ApppagesDashboardsSalesIndexRoute: ApppagesDashboardsSalesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
