import { baseNavigationObj } from "../baseNavigation";
import { NavigationTree } from "@/@types/navigation";

const ROOT_DASHBOARDS = "/dashboards";

const path = (root: string, item: string) => `${root}${item}`;

export const dashboards: NavigationTree = {
  ...baseNavigationObj["dashboards"],
  type: "root",
  childs: [
    {
      id: "dashboards.sales",
      path: path(ROOT_DASHBOARDS, "/sales"),
      type: "item",
      title: "Sales Overview",
      transKey: "nav.dashboards.sales",
      icon: "dashboards.sales",
    },
    {
      id: "dashboards.revenue",
      path: path(ROOT_DASHBOARDS, "/crm-analytics"),
      type: "item",
      title: "Revenue & Profits",
      transKey: "nav.dashboards.revenue",
      icon: "dashboards.revenue",
    },
    {
      id: "dashboards.channel",
      path: path(ROOT_DASHBOARDS, "/orders"),
      type: "item",
      title: "Sales by Channel",
      transKey: "nav.dashboards.channel",
      icon: "dashboards.channel",
    },
    {
      id: "dashboards.divide-1",
      type: "divider",
    },
    /* {
      id: "dashboards.crypto",
      path: path(ROOT_DASHBOARDS, "/crypto"),
      type: "collapse",
      title: "Cryptocurrency",
      transKey: "nav.dashboards.crypto",
      icon: "dashboards.crypto",
      childs: [
        {
          id: "dashboards.crypto-1",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/crypto/crypto-1"),
          title: "Cryptocurrency v1",
          transKey: "nav.dashboards.crypto-1",
        },
        {
          id: "dashboards.crypto-2",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/crypto/crypto-2"),
          title: "Cryptocurrency v2",
          transKey: "nav.dashboards.crypto-2",
        },
      ],
    }, 
    {
      id: "dashboards.banking",
      path: path(ROOT_DASHBOARDS, "/banking"),
      type: "collapse",
      title: "Cryptocurrency",
      transKey: "nav.dashboards.banking",
      icon: "dashboards.banking",
      childs: [
        {
          id: "dashboards.banking-1",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/banking/banking-1"),
          title: "Banking v1",
          transKey: "nav.dashboards.banking-1",
        },
        {
          id: "dashboards.banking-2",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/banking/banking-2"),
          title: "Banking v2",
          transKey: "nav.dashboards.banking-2",
        },
      ],
    },*/
    {
      id: "dashboards.branches",
      path: path(ROOT_DASHBOARDS, "/personal"),
      type: "item",
      title: "Branch Performance",
      transKey: "nav.dashboards.branches",
      icon: "dashboards.branches",
    },
    {
      id: "dashboards.top-products",
      path: path(ROOT_DASHBOARDS, "/cms-analytics"),
      type: "item",
      title: "Top Products",
      transKey: "nav.dashboards.top-products",
      icon: "dashboards.top-products",
    },
    {
      id: "dashboards.customer-activity",
      path: path(ROOT_DASHBOARDS, "/influencer"),
      type: "item",
      title: "Customer Activity",
      transKey: "nav.dashboards.customer-activity",
      icon: "dashboards.customer-activity",
    },
    {
      id: "dashboards.outstanding-payments",
      path: path(ROOT_DASHBOARDS, "/travel"),
      type: "item",
      title: "Outstanding Payments",
      transKey: "nav.dashboards.outstanding-payments",
      icon: "dashboards.outstanding-payments",
    },
    {
      id: "dashboards.low-stock-alerts",
      path: path(ROOT_DASHBOARDS, "/teacher"),
      type: "item",
      title: "LOw Stock Alerts",
      transKey: "nav.dashboards.low-stock-alerts",
      icon: "dashboards.low-stock-alerts",
    },
    {
      id: "dashboards.staff-activity",
      path: path(ROOT_DASHBOARDS, "/education"),
      type: "item",
      title: "Staff Activity",
      transKey: "nav.dashboards.staff-activity",
      icon: "dashboards.staff-activity",
    },
    {
      id: "dashboards.ai-sales-forecast",
      path: path(ROOT_DASHBOARDS, "/authors"),
      type: "item",
      title: "Ai Sales Forecast",
      transKey: "nav.dashboards.ai-sales-forecast",
      icon: "dashboards.ai-sales-forecast",
    },
   /*  {
      id: "dashboards.doctor",
      path: path(ROOT_DASHBOARDS, "/doctor"),
      type: "item",
      title: "Doctor",
      transKey: "nav.dashboards.doctor",
      icon: "dashboards.doctor",
    },
    {
      id: "dashboards.employees",
      path: path(ROOT_DASHBOARDS, "/employees"),
      type: "item",
      title: "Employees",
      transKey: "nav.dashboards.employees",
      icon: "dashboards.employees",
    },
    {
      id: "dashboards.workspaces",
      path: path(ROOT_DASHBOARDS, "/workspaces"),
      type: "item",
      title: "Workspaces",
      transKey: "nav.dashboards.workspaces",
      icon: "dashboards.workspaces",
    },
    {
      id: "dashboards.meetings",
      path: path(ROOT_DASHBOARDS, "/meetings"),
      type: "item",
      title: "Meetings",
      transKey: "nav.dashboards.meetings",
      icon: "dashboards.meetings",
    },
    {
      id: "dashboards.projects-board",
      path: path(ROOT_DASHBOARDS, "/projects-board"),
      type: "item",
      title: "Projects Board",
      transKey: "nav.dashboards.projects-board",
      icon: "dashboards.projects-board",
    },
    {
      id: "dashboards.divide-2",
      type: "divider",
    },
    {
      id: "dashboards.widget-ui",
      path: path(ROOT_DASHBOARDS, "/widget-ui"),
      type: "item",
      title: "Widgets UI",
      transKey: "nav.dashboards.widget-ui",
      icon: "dashboards.widget",
    },
    {
      id: "dashboards.widget-contact",
      path: path(ROOT_DASHBOARDS, "/widget-contact"),
      type: "item",
      title: "Widgets Contact",
      transKey: "nav.dashboards.widget-contact",
      icon: "dashboards.widget",
    }, */
  ],
};
